### PR TITLE
Renames update fixes #21

### LINKED ISSUE #21: rename update-dom
right now the update-dom file allows creating an update loop from a single element that prevents the tree from being dismounted when the type of root node is changed. This removes a lot of boilerplate when building applications. I think the file is rather unfortunately named though, so I reckon we should rename it.

- `require('nanomorph/loop')` (my preference)
- `require('nanomorph/update')`

thoughts? cc/ @kristoferjoseph

### PR DESCRIPTION
**Pull request by kristoferjoseph**

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
sweet, this would be a semver major tho - do it?

**Comment by yoshuawuyts** [comment]
(I think we should. Merging!)

**Comment by kristoferjoseph** [comment]
I guess so huh, since the API changed.

**Comment by yoshuawuyts** [comment]
`nanomorph@2.0.0` :tada:

**Pull request merged**
