### PR TITLE
Libify

### LINKED ISSUE #38: [bug] copyAttributeNS only works on DOM nodes created with min-document
```js
  var newAttrs = newNode._attributes
  var oldAttrs = oldNode._attributes
  var mergedAttrs = xtend(newAttrs, oldAttrs)
```

The `_attributes` value only exists on DOM nodes created with `min-document` / `bel` which is fine  - but once we use `yo-yoify` or native DOM nodes this'll break down.

### LINKED ISSUE #39: test attribute copying
We're testing SVG namespaces and events, but not regular ol' attributes. I've been running into issues on the server with this, so we should probably test this. Would also help enable #37 as we need to read and write attributes.

Specifically it'd be nice if tests could hit `el.setAttribute()` and `el.getAttribute()`. Thanks!

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Closes #38, closes #39 - need to fix the final tests (stringifying nodes doesn't always line up) but yeah at least the code now works! :D

### CODE REVIEW

**Comment by timwis** [comment]
aw, man, was really looking forward to finding out what this new browserify transform "libify" is

**Comment by yoshuawuyts** [comment]
Haha, sorry to disappoint :P

**Comment by yoshuawuyts** [comment]
Allllright, this should be done :D

**Comment by yoshuawuyts** [comment]
Open for 24 hours now; people seem happy - merging!

**Pull request merged**
